colors = [
    [255, 0, 0],
    [0, 255, 0],
    [0, 0, 255],
]

[messages]
messages = [
    "TEST MESSAGE 1!",
    "TEST MESSAGE 2!",
    "TEST MESSAGE 3!",
    "TEST MESSAGE 4!",
]
separator = "    "
typeface = "freeserif"
size = 350
bold = true
italic = false
anti-aliasing = false
scroll_speed = 240
outline_width = 3
outline_colors = [
    [0, 0, 0],
    [255, 255, 255],
]

[images]
sources = [
    ["pic1.svg", 64],
    ["pic2.bmp", -1],
    ["pic3.bmp", 10],
]
number = 10
reposition_attempts = -1

[timings]
fps = 30
image_change_time = 2
color_change_time = 15