# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: check-added-large-files
    -   id: check-yaml
    -   id: check-ast
    -   id: check-docstring-first
-   repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
    -   id: mypy
        files: ^src/
-   repo: https://github.com/PyCQA/pylint
    rev: v3.1.0
    hooks:
    -   id: pylint
        args: [-j 0, --errors-only, --disable=import-error]
        files: ^src/
-   repo: local
    hooks:
    -   id: tox check not slow
        name: tox-check-pre-commit
        entry: tox -p -- -m "not slow"
        language: system
        types: [python]
        pass_filenames: false
        stages:
            - pre-commit
    -   id: tox check
        name: tox-pre-push
        entry: tox -p
        language: system
        types: [ python ]
        pass_filenames: false
        stages:
            - pre-push
