[tool.poetry]
name = "screen-animator"
version = "0.1.0"
description = ""
license = "MIT"
authors = ["David Anscombe <dave.anski@gmail.com>"]
repository = "https://github.com/Anski-D/screen_animator"
packages = [
    { include = "screen_animator", from = "src" },
]
include = [
    { path = "example", format = ["sdist", "wheel"] }
]

[tool.poetry.scripts]
copy_examples = "screen_animator:copy_examples"

[tool.poetry.dependencies]
python = "^3.10"
pygame = "^2.1.2"
tomli = "^2.0.1"

[tool.poetry.group.dev.dependencies]
pytest = "^7.1.2"
pylint = "^2.14.5"
mypy = "^0.971"
black = "^22.6.0"
pytest-cov = "^3.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
