[project]
name = "screen_animator"
version = "0.10.1a0"
description = "Python package to generate animated messages and images on a screen, with a focus on the Raspberry Pi."
license = "MIT"
authors = ["Dave Anscombe <dave.anski@gmail.com>"]
readme = "README.md"
repository = "https://github.com/Anski-D/screen_animator"
requires-python = ">=3.10"
dependencies = []

[project.scripts]
screen-animator = "screen_animator:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
