[tool.poetry]
name = "screen_animator"
version = "0.1.0"
description = ""
authors = ["David Anscombe <dave.anski@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
pygame = "^2.1.2"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
pylint = "^2.14.5"
mypy = "^0.971"
black = "^22.6.0"
pytest-cov = "^3.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
