[tool.poetry]
name = "screen-animator"
version = "0.9.0"
description = ""
license = "MIT"
authors = ["David Anscombe <dave.anski@gmail.com>"]
readme = "README.md"
repository = "https://github.com/Anski-D/screen_animator"
packages = [
    { include = "screen_animator", from = "src" },
]
include = [
    { path = "example", format = ["sdist", "wheel"] },
]

[tool.poetry.scripts]
copy_examples = "screen_animator:copy_examples"

[tool.poetry.dependencies]
python = "^3.10"
pygame-ce = "^2.4.0"
numpy = "^1.26.4"
cairosvg = "^2.7.1"
svgutils = "^0.3.4"
tomli = { version = "^2.0.1", python = "<3.11" }

[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
pytest = "^8.0.0"
pytest-cov = "^4.1.0"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
pylint = "^3.0.3"
mypy = "^1.8.0"
black = "^24.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
markers = [
    "slow: tests that are slow",
]